### PR TITLE
Auto-configuration and starter for Ollama

### LINKED ISSUE #68: Create boot starter for Ollama client

### PR DESCRIPTION
**Pull request by shakuzen**
Adds auto-configuration and a starter for Ollama.

Resolves #68

### CODE REVIEW

**Comment by shakuzen** [comment]
I've rebased on the latest `main` but I'm getting errors in the tests of Transformers Embedding, which I haven't touched with my changes, so I don't think the failures are related. Does CI not run against pull requests?

**Comment by tzolov** [comment]
Hi @shakuzen , thank you for the contribution. I will have a look shortly. 
Can you share the Transformers Embedding error and what OS are running on?

**Comment by tzolov** [comment]
Rebased, squashed and merged at 6bdea65cd50759249db509fbaa3f5393be741f95

**Comment by shakuzen** [comment]
> Can you share the Transformers Embedding error and what OS are running on?

I'm on an apple silicon MBP.

```
[ERROR] Failures: 
[ERROR]   TransformersEmbeddingClientTests.embed:38 
expected: -0.19744634628295898
 but was: -0.19744601845741272
[ERROR]   TransformersEmbeddingClientTests.embedDocument:48 
expected: -0.19744634628295898
 but was: -0.19744601845741272
[ERROR]   TransformersEmbeddingClientTests.embedForResponse:78 
expected: -0.19744634628295898
 but was: -0.19744601845741272
[ERROR]   TransformersEmbeddingClientTests.embedList:59 
expected: -0.19744634628295898
 but was: -0.19744601845741272
[INFO] 
[ERROR] Tests run: 9, Failures: 4, Errors: 0, Skipped: 0
```

**Comment by tzolov** [comment]
thanks @shakuzen , 
Apparently, there is a rounding discrepancy, after the 6th digit, for the different platforms.  
Have to adjust the tests

**Comment by tzolov** [comment]
should be fixed now.

**Comment by shakuzen** [comment]
The tests are passing for me now.

**Comment by tzolov** [comment]
Cool! Thanks. 
Now the thread is officially closed.

**Pull request closed without merging**
